name: abramenko.me
static_sites:
    - build_command: rm -r ./public; hugo --destination ./public
      environment_slug: hugo
      envs:
          - key: HUGO_VERSION
            scope: BUILD_TIME
            value: 0.92.0
      github:
          branch: main
          deploy_on_push: true
          repo: vaxann/abramenko.me
      name: abramenko.me
