name: abramenko.me
static_sites:
    - build_command: echo "Building with Hugo ${HUGO_VERSION} Extended=${HUGO_EXTENDED}" && hugo --destination ./public
      environment_slug: hugo
      github:
          branch: main
          deploy_on_push: true
          repo: vaxann/abramenko.me
      name: abramenko.me
      build_env:
        - key: HUGO_VERSION
          value: "0.147.2"
        - key: HUGO_EXTENDED
          value: "1"
